name = "politopics-frontend"
main = "workers/spa-r2-proxy.js"
compatibility_date = "2024-09-02"

[env.stage]
name = "politopics-frontend-stage"
r2_buckets = [{ binding = "ASSETS", bucket_name = "politopics-frontend-stage" }]

[env.prod]
name = "politopics-frontend-prod"
r2_buckets = [{ binding = "ASSETS", bucket_name = "politopics-frontend-prod" }]
