name = "politopics-frontend"
main = "workers/spa-r2-proxy.js"
compatibility_date = "2024-09-02"

[env.local]
name = "politopics-frontend-local"
r2_buckets = [{ binding = "ASSETS", bucket_name = "politopics-frontend-local" }]
[env.local.vars]
ASSET_BASE_URL = "http://localhost:4570"

[env.stage]
name = "politopics-frontend-stage"
r2_buckets = [{ binding = "ASSETS", bucket_name = "politopics-frontend-stage" }]

[env.prod]
name = "politopics-frontend-prod"
r2_buckets = [{ binding = "ASSETS", bucket_name = "politopics-frontend-prod" }]
routes = [
    { pattern = "politopics.net", custom_domain = true}
]
